2025-04-24T23:16:34.244761-0300 INFO 2
2025-04-24T23:16:34.244761-0300 INFO 3
2025-04-24T23:17:08.360381-0300 INFO 2
2025-04-24T23:17:08.360381-0300 INFO 3
2025-04-24T23:17:08.360381-0300 ERROR An error has been caught in function '<module>', process 'MainProcess' (27456), thread 'MainThread' (4756):
Traceback (most recent call last):

> File "D:\workspace\jornada\bc_python\bc_python_aula09\exemplo_00.py", line 15, in <module>
    soma(2,'3')
    └ <function soma at 0x000002020D4B65C0>

  File "D:\workspace\jornada\bc_python\bc_python_aula09\exemplo_00.py", line 12, in soma
    logger.info(x + y)
    │      │    │   └ '3'
    │      │    └ 2
    │      └ <function Logger.info at 0x000002020D4B6020>
    └ <loguru.logger handlers=[(id=0, level=10, sink=<stderr>), (id=1, level=20, sink='meu.log')]>

TypeError: unsupported operand type(s) for +: 'int' and 'str'
